-- CamiCup - esquema completo no destructivo.
-- Puede ejecutarse en un proyecto nuevo. Si las tablas ya existen, conserva los datos.

create table if not exists public.teams (
  id text primary key,
  name text not null,
  short_name text,
  group_name text,
  captain text,
  logo text,
  mmr_total numeric default 0,
  active boolean default true,
  accent text
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  team_id text references public.teams(id) on delete cascade,
  nickname text not null,
  role text,
  mmr numeric default 0,
  dota_id text,
  is_captain boolean default false
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  match_date date not null,
  match_time time not null,
  team_a text references public.teams(id),
  team_b text references public.teams(id),
  score_a integer default 0,
  score_b integer default 0,
  best_of integer default 3,
  stage text default 'Todos contra todos',
  status text default 'Programado',
  group_name text,
  stream_url text,
  created_at timestamptz default now()
);

create table if not exists public.tournament_config (
  id integer primary key default 1,
  tournament_name text default 'CamiCup',
  edition text default 'Primera edición',
  subtitle text default 'Primera edición oficial de CamiCup',
  team_count integer default 6,
  start_date date,
  final_date date,
  prize_first numeric default 700,
  prize_second numeric default 150,
  kick_channel text default 'fortuna2121',
  points_per_win integer default 1,
  pause_count integer default 2,
  pause_minutes integer default 10,
  lobby_tolerance integer default 15,
  registration_open boolean default true,
  rules jsonb default '[]'::jsonb
);

-- Añade columnas si el esquema inicial ya había sido creado antes.
alter table public.teams add column if not exists accent text;
alter table public.matches add column if not exists stream_url text;
alter table public.tournament_config add column if not exists edition text default 'Primera edición';
alter table public.tournament_config add column if not exists subtitle text default 'Primera edición oficial de CamiCup';
alter table public.tournament_config add column if not exists team_count integer default 6;
alter table public.tournament_config add column if not exists pause_count integer default 2;
alter table public.tournament_config add column if not exists pause_minutes integer default 10;
alter table public.tournament_config add column if not exists lobby_tolerance integer default 15;
alter table public.tournament_config add column if not exists registration_open boolean default true;
alter table public.tournament_config add column if not exists rules jsonb default '[]'::jsonb;

alter table public.teams enable row level security;
alter table public.players enable row level security;
alter table public.matches enable row level security;
alter table public.tournament_config enable row level security;

-- Lectura pública.
drop policy if exists "public read teams" on public.teams;
drop policy if exists "public read players" on public.players;
drop policy if exists "public read matches" on public.matches;
drop policy if exists "public read config" on public.tournament_config;
create policy "public read teams" on public.teams for select to anon, authenticated using (true);
create policy "public read players" on public.players for select to anon, authenticated using (true);
create policy "public read matches" on public.matches for select to anon, authenticated using (true);
create policy "public read config" on public.tournament_config for select to anon, authenticated using (true);

-- Escritura para usuarios autenticados de administración.
drop policy if exists "admin teams" on public.teams;
drop policy if exists "admin players" on public.players;
drop policy if exists "admin matches" on public.matches;
drop policy if exists "admin config" on public.tournament_config;
create policy "admin teams" on public.teams for all to authenticated using (true) with check (true);
create policy "admin players" on public.players for all to authenticated using (true) with check (true);
create policy "admin matches" on public.matches for all to authenticated using (true) with check (true);
create policy "admin config" on public.tournament_config for all to authenticated using (true) with check (true);

-- Realtime: agrega solo las tablas que aún no pertenecen a la publicación.
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='teams') then alter publication supabase_realtime add table public.teams; end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='players') then alter publication supabase_realtime add table public.players; end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='matches') then alter publication supabase_realtime add table public.matches; end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='tournament_config') then alter publication supabase_realtime add table public.tournament_config; end if;
end $$;
